version: "3.7"

services:
  config-server:
    # image: docker.io/library/configserver:0.0.1-SNAPSHOT
    image: micro/config-server:0.0.1-SNAPSHOT
    ports:
      - "8071:8071"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
        aliases:
          - "config-server"
  eureka-server:
    # image: docker.io/library/configserver:0.0.1-SNAPSHOT
    image: micro/eureka-server:0.0.1-SNAPSHOT
    depends_on:
      - config-server
    ports:
      - "8070:8070"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
        aliases:
          - "eureka-server"

networks:
  backend:
    driver: bridge
