spring:
  application:
    name: config-server
  profiles:
    active:
      - native, git
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/johatfie/microservices-properties.git
          #searchPaths: eureka-server,gateway-server
    bus:
      enabled: true
      refresh:
        enabled: true
    stream:
      kafka:
        binder:
          zkNodes: localhost:9092 #,127.0.0.1:9092
          brokers: localhost:2181 #,127.0.1:2181

server:
  port: 8071

#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"

